
font_family JetBrainsMono Nerd Font
font_size 12

background_opacity 0.90
dynamic_background_opacity yes

remember_window_size yes
initial_window_width 900
initial_window_height 600

scrollback_lines 5000

foreground #ffffff
background #000000
selection_background #ffffff
selection_foreground #ffffff

color0 #000000
color1 #cd0000
color2 #00cd00
color3 #cdcd00
color4 #0000cd
color5 #cd00cd
color6 #00cdcd
color7 #e5e5e5
color8 #7f7f7f
color9 #ff0000
color10 #00ff00
color11 #ffff00
color12 #0000ff
color13 #ff00ff
color14 #00ffff
color15 #ffffff

startup_session none

window_margin_width 9
window_padding_width 5
